// Mocks generated by Mockito 5.4.6 from annotations
// in fitness_app/test/features/food_details/presentation/view_model/food_details_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fitness_app/config/base_response/base_response.dart' as _i5;
import 'package:fitness_app/features/food_details/domain/entities/meal_entity.dart'
    as _i6;
import 'package:fitness_app/features/food_details/domain/repo/food_details_repo.dart'
    as _i2;
import 'package:fitness_app/features/food_details/domain/use_cases/get_meal_details_use_case.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFoodDetailsRepoContract_0 extends _i1.SmartFake
    implements _i2.FoodDetailsRepoContract {
  _FakeFoodDetailsRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetMealDetailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMealDetailsUseCase extends _i1.Mock
    implements _i3.GetMealDetailsUseCase {
  MockGetMealDetailsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FoodDetailsRepoContract get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeFoodDetailsRepoContract_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.FoodDetailsRepoContract);

  @override
  _i4.Future<_i5.BaseResponse<_i6.MealEntity>> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i4.Future<_i5.BaseResponse<_i6.MealEntity>>.value(
              _i7.dummyValue<_i5.BaseResponse<_i6.MealEntity>>(
                this,
                Invocation.method(#call, [id]),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.MealEntity>>);
}
